# Generated by Django 5.0.3 on 2024-03-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=150)),
                ('m_id', models.CharField(max_length=150)),
                ('s_msg', models.CharField(max_length=150)),
                ('m_msg', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='addcoordinator',
        ),
        migrations.DeleteModel(
            name='addnews',
        ),
        migrations.AddField(
            model_name='bookedstudents',
            name='name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tests',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
